const input=document.getElementById('urlInput');const pasteBtn=document.getElementById('pasteBtn');const results=document.getElementById('results');const status=document.getElementById('status');const removedText=document.getElementById('removedText');const resetBtn=document.getElementById('resetBtn');const toast=document.getElementById('toast');const destinationGrid=document.getElementById('destinationGrid');
const trackers=['fbclid','gclid','dclid','msclkid','mc_cid','mc_eid','igshid','vero_id','oly_anon_id','oly_enc_id','wickedid','yclid','twclid','ttclid','_hsenc','_hsmi','mkt_tok'];
const trackerPrefixes=['utm_','ga_','pk_'];
const storageKey='linkready:lastFormat';
let formats={};let topFormat='clean';
function normalize(raw){let value=raw.trim();if(!value)return null;if(!/^https?:\/\//i.test(value))value='https://'+value;try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url:null}catch{return null}}
function cleanUrl(url){const clone=new URL(url.toString());let removed=0;[...clone.searchParams.keys()].forEach(k=>{const key=k.toLowerCase();if(trackers.includes(key)||trackerPrefixes.some(prefix=>key.startsWith(prefix))){clone.searchParams.delete(k);removed++}});if(clone.hash&&/^#(?:utm_|ref(?:errer)?=|fbclid=|gclid=)/i.test(clone.hash)){clone.hash='';removed++}return{url:clone.toString(),removed}}
function labelFor(url){const path=url.pathname.replace(/\/$/,'');const tail=decodeURIComponent(path.split('/').filter(Boolean).pop()||'');return tail?tail.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()):url.hostname.replace(/^www\./,'')}
function rememberFormat(format){try{localStorage.setItem(storageKey,format)}catch{}}
function getRememberedFormat(){try{return localStorage.getItem(storageKey)||'clean'}catch{return'clean'}}
function applyRememberedOrder(){const wanted=getRememberedFormat();const card=destinationGrid.querySelector(`[data-card-format="${wanted}"]`)||destinationGrid.querySelector('[data-card-format="clean"]');destinationGrid.querySelectorAll('.destination-card').forEach(c=>c.classList.remove('featured'));if(card){destinationGrid.prepend(card);card.classList.add('featured');topFormat=card.dataset.cardFormat||'clean'}}
function updateSimulatedPreviews(title,clean){const url=new URL(clean);document.querySelectorAll('.platform-preview').forEach(box=>{const titleEl=box.querySelector('.sim-title');const domainEl=box.querySelector('.sim-domain');if(titleEl)titleEl.textContent=title;if(domainEl)domainEl.textContent=url.hostname.replace(/^www\./,'')})}
function render(){status.textContent='';const parsed=normalize(input.value);if(!parsed){results.classList.add('hidden');if(input.value.trim())status.textContent='Enter a valid web link.';return}const cleaned=cleanUrl(parsed);const clean=cleaned.url;const title=labelFor(new URL(clean));formats={clean,whatsapp:`${title}\n${clean}`,email:`${title} — ${clean}`,linkedin:`${title}\n${clean}`,markdown:`[${title}](${clean})`};document.getElementById('cleanPreview').textContent=formats.clean;document.getElementById('whatsappPreview').textContent=formats.whatsapp;document.getElementById('emailPreview').textContent=formats.email;document.getElementById('linkedinPreview').textContent=formats.linkedin;document.getElementById('markdownPreview').textContent=formats.markdown;updateSimulatedPreviews(title,clean);removedText.textContent=cleaned.removed?`${cleaned.removed} tracking parameter${cleaned.removed===1?'':'s'} removed`:'Already clean — no common tracking parameters found';results.classList.remove('hidden')}
async function copyText(text,button,format){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}if(format)rememberFormat(format);if(button){const original=button.dataset.original||button.textContent;button.dataset.original=original;button.textContent='✓ Copied';button.classList.remove('copied');void button.offsetWidth;button.classList.add('copied','confirming');clearTimeout(button._resetTimer);button._resetTimer=setTimeout(()=>{button.textContent=original;button.classList.remove('copied','confirming')},1500)}showToast('Copied to clipboard')}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1600)}
function copyTopFormat(){const format=topFormat&&formats[topFormat]?topFormat:'clean';const button=document.querySelector(`.copy-btn[data-format="${format}"]`);if(formats[format])copyText(formats[format],button,format)}
input.addEventListener('input',render);
input.addEventListener('paste',()=>setTimeout(render,0));
pasteBtn.addEventListener('click',async()=>{status.textContent='';try{const text=await navigator.clipboard.readText();input.value=text;render()}catch{input.focus();status.textContent='Paste from your clipboard into the field above.'}});
document.addEventListener('paste',e=>{if(e.target===input)return;const text=e.clipboardData&&e.clipboardData.getData('text');if(!text)return;e.preventDefault();input.value=text;render();input.focus()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();copyTopFormat()}});
document.querySelectorAll('.copy-btn').forEach(btn=>btn.addEventListener('click',()=>{const format=btn.dataset.format;if(formats[format])copyText(formats[format],btn,format)}));
resetBtn.addEventListener('click',()=>{input.value='';formats={};results.classList.add('hidden');status.textContent='';input.focus()});
applyRememberedOrder();
