const $=id=>document.getElementById(id),input=$('urlInput'),results=$('results'),status=$('status'),toast=$('toast');
const KEYS={count:'linkready:cleanCount',history:'linkready:history',settings:'linkready:settings',stats:'linkready:stats'};
const formatDefs=[['clean','Clean link','A clean URL for anywhere.'],['whatsapp','WhatsApp','Readable two-line share.'],['email','Email','A tidy labeled link.'],['linkedin','LinkedIn','Clean professional sharing.'],['markdown','Markdown','For docs, notes and GitHub.'],['html','HTML','Ready for websites and newsletters.'],['slack','Slack / Discord','Compact chat-ready sharing.'],['reddit','Reddit','Markdown-style post link.'],['sms','SMS','Short, simple text message.'],['plain','Plain text','Label and URL on separate lines.']];
let current=null,formats={},batchItems=[],deferredInstallPrompt=null,lastSource='';
const get=(k,f)=>{try{const v=localStorage.getItem(k);return v===null?f:v}catch{return f}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const parseList=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
function settings(){try{return{preset:'standard',customRemove:[],preserve:[],...JSON.parse(get(KEYS.settings,'{}'))}}catch{return{preset:'standard',customRemove:[],preserve:[]}}}
function stats(){try{return{cleaned:0,removed:0,chars:0,...JSON.parse(get(KEYS.stats,'{}'))}}catch{return{cleaned:0,removed:0,chars:0}}}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1700)}
async function copy(text,button){try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove()}if(button){const old=button.textContent;button.textContent='✓ Copied';setTimeout(()=>button.textContent=old,1400)}showToast('Copied to clipboard')}
function valid(raw){const u=LinkReadyCleaner.normalize(raw);return u&&u.hostname.includes('.')&&!/\s/.test(u.hostname)?u:null}
function titleFor(u){const custom=$('customLabel').value.trim();if(custom)return custom;const tail=decodeURIComponent(u.pathname.split('/').filter(Boolean).pop()||'');return(tail?tail.replace(/[-_]+/g,' '):u.hostname.replace(/^www\./,'')).replace(/\b\w/g,c=>c.toUpperCase())}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function buildFormats(url){const u=new URL(url),title=titleFor(u);formats={clean:url,whatsapp:`${title}\n${url}`,email:`${title} — ${url}`,linkedin:`${title}\n${url}`,markdown:`[${title}](${url})`,html:`<a href="${url}">${escapeHtml(title)}</a>`,slack:`${title} — ${url}`,reddit:`[${title}](${url})`,sms:`${title}: ${url}`,plain:`${title}\n${url}`}}
function renderCards(){const grid=$('destinationGrid');grid.innerHTML='';formatDefs.forEach(([key,name,desc],i)=>{const card=document.createElement('article');card.className='destination-card'+(i===0?' featured':'');card.innerHTML=`<div class="destination-top"><span class="destination-icon">${i?name.slice(0,2):'✓'}</span><div><h2>${name}</h2><p>${desc}</p></div></div><div class="preview"></div><button class="copy-btn" type="button">Copy ${name}</button>`;card.querySelector('.preview').textContent=formats[key];card.querySelector('button').onclick=e=>copy(formats[key],e.currentTarget);grid.append(card)})}
function renderExplain(report){$('destinationHost').textContent=report.host;$('explainGrid').innerHTML=`<div><span>Destination</span><strong>${escapeHtml(report.host)}</strong></div><div><span>Protocol</span><strong>${report.protocol.replace(':','').toUpperCase()}</strong></div><div><span>Redirect wrappers</span><strong>${report.redirects.length}</strong></div><div><span>Fragment</span><strong>${report.fragment?'Preserved':'None'}</strong></div>`;const list=$('parameterList');list.innerHTML=report.parameters.length?report.parameters.map(p=>`<div><code>${escapeHtml(p.name)}</code><span class="tag ${p.kind}">${p.kind}</span><small>${escapeHtml(p.value||'')}</small></div>`).join(''):'<p>No query parameters in this link.</p>';const warnings=[...report.warnings];$('safetyTitle').textContent=warnings.length?'Check this destination':'Destination checked locally';$('edgeNotice').textContent=warnings.join(' ');$('safetyCard').classList.toggle('warning',warnings.length>0)}
function renderQr(url){const box=$('qrCode');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:url,width:152,height:152,colorDark:'#111827',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
function updateSummary(report){const n=report.cleaned.removed.length;$('removedText').textContent=n?`${n} tracking parameter${n===1?'':'s'} removed`:'Already clean';$('removedParams').textContent=n?`Removed: ${report.cleaned.removed.join(', ')}`:'No known tracking parameters were found.'}
function history(){try{const h=JSON.parse(get(KEYS.history,'[]'));return Array.isArray(h)?h:[]}catch{return[]}}
function saveHistory(report){const list=history().filter(x=>x.clean!==report.destination);list.unshift({source:report.original,clean:report.destination,removed:report.cleaned.removed,platform:report.cleaned.platform,time:Date.now()});set(KEYS.history,JSON.stringify(list.slice(0,12)));renderHistory()}
function renderHistory(){const items=history(),section=$('historySection'),list=$('historyList');section.classList.toggle('hidden',!items.length);list.innerHTML='';items.forEach(item=>{const row=document.createElement('div');row.className='history-item';row.innerHTML=`<div class="history-meta"><code></code><small>${escapeHtml(item.platform||'Generic')} · ${item.removed.length?`Removed ${item.removed.join(', ')}`:'Already clean'}</small></div><button class="history-copy" type="button">Copy</button>`;row.querySelector('code').textContent=item.clean;row.querySelector('button').onclick=e=>copy(item.clean,e.currentTarget);list.append(row)})}
function updateStats(report){const s=stats();s.cleaned++;s.removed+=report.cleaned.removed.length;s.chars+=Math.max(0,report.original.length-report.destination.length);set(KEYS.stats,JSON.stringify(s));renderStats()}
function renderStats(){const s=stats();$('statCleaned').textContent=s.cleaned;$('statRemoved').textContent=s.removed;$('statChars').textContent=s.chars;$('cleanCount').textContent=`${s.cleaned} link${s.cleaned===1?'':'s'} cleaned on this device`}
function cleanOne(raw,{count=true}={}){const parsed=valid(raw);if(!parsed){results.classList.add('hidden');status.textContent=raw?'Enter a valid web address, such as https://example.com.':'';return null}const report=LinkReadyCleaner.inspect(parsed.toString(),settings());if(!report)return null;current=report;input.value=report.original;buildFormats(report.destination);renderCards();renderExplain(report);renderQr(report.destination);updateSummary(report);results.classList.remove('hidden');status.textContent='';$('pasteBtn').textContent='Clean link';if(count&&lastSource!==report.original){lastSource=report.original;updateStats(report);saveHistory(report)}return report}
function reset(){input.value='';current=null;formats={};lastSource='';results.classList.add('hidden');status.textContent='';$('pasteBtn').textContent='Paste';input.focus()}
input.addEventListener('input',()=>{const has=input.value.trim();$('pasteBtn').textContent=has?'Clean link':'Paste';if(has)status.textContent=''});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.metaKey&&!e.ctrlKey){e.preventDefault();cleanOne(input.value)}});
$('pasteBtn').onclick=async()=>{if(input.value.trim())return cleanOne(input.value);$('clipboardBtn').click()};$('clipboardBtn').onclick=async()=>{try{input.value=await navigator.clipboard.readText();cleanOne(input.value)}catch{status.textContent='Clipboard access was unavailable. Paste into the field instead.'}};
document.addEventListener('paste',e=>{if(e.target===input||e.target===$('batchInput'))return;const t=e.clipboardData?.getData('text');if(t){e.preventDefault();input.value=t;cleanOne(t);input.focus()}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();if(formats.clean)copy(formats.clean,document.querySelector('.copy-btn'))}if(e.key==='Escape'&&!results.classList.contains('hidden'))reset()});
$('resetBtn').onclick=reset;$('undoBtn').onclick=()=>{if(current){input.value=current.original;results.classList.add('hidden');status.textContent='Original link restored. Clean again when ready.'}};$('customLabel').oninput=()=>{if(current){buildFormats(current.destination);renderCards()}};
$('nativeShareBtn').onclick=async()=>{if(!current)return;if(navigator.share){try{await navigator.share({title:titleFor(new URL(current.destination)),url:current.destination})}catch{}}else copy(current.destination)};
$('downloadQrBtn').onclick=()=>{const canvas=$('qrCode').querySelector('canvas'),img=$('qrCode').querySelector('img');const href=canvas?.toDataURL('image/png')||img?.src;if(!href)return;const a=document.createElement('a');a.href=href;a.download='linkready-qr.png';a.click()};
$('batchToggle').onclick=()=>{$('batchPanel').classList.toggle('hidden')};$('batchCleanBtn').onclick=()=>{batchItems=$('batchInput').value.split(/\n+/).map(v=>v.trim()).filter(Boolean).map(source=>{const u=valid(source),r=u&&LinkReadyCleaner.inspect(u.toString(),settings());return{source,clean:r?.destination||'',removed:r?.cleaned.removed||[],valid:!!r}});$('batchResults').innerHTML=batchItems.map(x=>`<div class="batch-row ${x.valid?'':'invalid'}"><span>${escapeHtml(x.valid?x.clean:`Invalid: ${x.source}`)}</span><small>${x.valid?`${x.removed.length} removed`:'Check this link'}</small></div>`).join('');$('batchCopyBtn').hidden=$('batchExportBtn').hidden=!batchItems.some(x=>x.valid)};$('batchCopyBtn').onclick=e=>copy(batchItems.filter(x=>x.valid).map(x=>x.clean).join('\n'),e.currentTarget);$('batchExportBtn').onclick=()=>download('linkready-cleaned.csv','text/csv','original,cleaned,removed\n'+batchItems.map(x=>[x.source,x.clean,x.removed.join('|')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'));
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('settingsToggle').onclick=()=>{$('settingsPanel').classList.toggle('hidden');$('settingsToggle').textContent=$('settingsPanel').classList.contains('hidden')?'Show settings':'Hide settings'};function fillSettings(){const s=settings();$('presetSelect').value=s.preset;$('customRemove').value=s.customRemove.join(', ');$('customPreserve').value=s.preserve.join(', ')}fillSettings();$('saveSettingsBtn').onclick=()=>{set(KEYS.settings,JSON.stringify({preset:$('presetSelect').value,customRemove:parseList($('customRemove').value),preserve:parseList($('customPreserve').value)}));showToast('Cleaning preferences saved');if(input.value)cleanOne(input.value,{count:false})};$('exportSettingsBtn').onclick=()=>download('linkready-settings.json','application/json',JSON.stringify(settings(),null,2));$('importSettingsInput').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());set(KEYS.settings,JSON.stringify(s));fillSettings();showToast('Settings imported')}catch{showToast('That settings file is not valid')}};$('resetSettingsBtn').onclick=()=>{localStorage.removeItem(KEYS.settings);fillSettings();showToast('Settings reset')};
$('clearHistoryBtn').onclick=()=>{set(KEYS.history,'[]');renderHistory();showToast('Local history cleared')};$('bookmarkletLink').href=LinkReadyCleaner.bookmarklet();$('bookmarkletLink').onclick=e=>{if(!e.altKey&&!e.metaKey&&!e.ctrlKey){e.preventDefault();showToast('Drag this button to your bookmarks bar')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderHistory();renderStats();const shared=new URLSearchParams(location.search);const sharedUrl=shared.get('url')||shared.get('text');if(shared.get('share-target')==='1'&&sharedUrl){input.value=sharedUrl;cleanOne(sharedUrl);history.replaceState({},'',location.pathname)}
